// <auto-generated />
using System;
using EChallan.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EChallan.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220818150336_Intial")]
    partial class Intial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EChallan.Web.Models.ChallaNumberDetail", b =>
                {
                    b.Property<int>("CID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChallanNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IssueIID")
                        .HasColumnType("int");

                    b.Property<string>("VehicalNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CID");

                    b.HasIndex("IssueIID");

                    b.ToTable("ChallaNumberDetails");
                });

            modelBuilder.Entity("EChallan.Web.Models.ChallanDetails", b =>
                {
                    b.Property<int>("CDID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("IID")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("CDID");

                    b.HasIndex("CID");

                    b.HasIndex("IID");

                    b.ToTable("ChallaDetails");
                });

            modelBuilder.Entity("EChallan.Web.Models.Issue", b =>
                {
                    b.Property<int>("IID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Issues")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("IID");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("EChallan.Web.Models.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("MethodEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentMethodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("PaymentMethodId");

                    b.HasIndex("Price");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("EChallan.Web.Models.ChallaNumberDetail", b =>
                {
                    b.HasOne("EChallan.Web.Models.Issue", null)
                        .WithMany("ChallaNumberDetails")
                        .HasForeignKey("IssueIID");
                });

            modelBuilder.Entity("EChallan.Web.Models.ChallanDetails", b =>
                {
                    b.HasOne("EChallan.Web.Models.ChallaNumberDetail", "ChallaNumberDetail")
                        .WithMany("ChallanDetails")
                        .HasForeignKey("CID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EChallan.Web.Models.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EChallan.Web.Models.PaymentMethod", b =>
                {
                    b.HasOne("EChallan.Web.Models.ChallanDetails", "ChallanDetails")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("Price")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
